export const AccountData = [
    {
        "MasterGroupId": "M1",
        "MasterGroup": "Liabilities",
        "AccountGroup": "CAPITAL ACCOUNT",
        "AccountGroupId": "A001",
        "AccountId": "L00511",
        "AccountHead": "CAPITAL ACCOUNT - Khalid",
        "AccountHeadArabic": "كابيتال أكونت - خالد",
        "ReferenceNo": "REF0001235",
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M1",
        "MasterGroup": "Liabilities",
        "AccountGroup": "CAPITAL ACCOUNT",
        "AccountGroupId": "A001",
        "AccountId": "L01016",
        "AccountHead": "Drawings Account - Mr Khalid",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M1",
        "MasterGroup": "Liabilities",
        "AccountGroup": "CAPITAL ACCOUNT",
        "AccountGroupId": "A001",
        "AccountId": "L01177",
        "AccountHead": "Capital Account - Abdullah Saeed",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M1",
        "MasterGroup": "Equity",
        "AccountGroup": "CAPITAL ACCOUNT",
        "AccountGroupId": "A001",
        "AccountId": "L01209",
        "AccountHead": "Owner Current Account",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M1",
        "MasterGroup": "Equity",
        "AccountGroup": "Profit & Loss Account",
        "AccountGroupId": "A030",
        "AccountId": "L00502",
        "AccountHead": "Retained Profits",
        "AccountHeadArabic": "الأرباح المحتجزة",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M1",
        "MasterGroup": "Equity",
        "AccountGroup": "Owner Current Account",
        "AccountGroupId": "A099",
        "AccountId": null,
        "AccountHead": null,
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M11",
        "MasterGroup": "Current Liabilites",
        "AccountGroup": null,
        "AccountGroupId": null,
        "AccountId": null,
        "AccountHead": null,
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M12",
        "MasterGroup": "Non Current Liabilities",
        "AccountGroup": "Goods in Transit",
        "AccountGroupId": "A098",
        "AccountId": "L00401",
        "AccountHead": "Goods in Transit - Transportation Cost",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M12",
        "MasterGroup": "Non Current Liabilities",
        "AccountGroup": "Goods in Transit",
        "AccountGroupId": "A098",
        "AccountId": "L00402",
        "AccountHead": "Goods in Transit - Customs Duty",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "LOANS & LIABILITIES",
        "AccountGroupId": "A002",
        "AccountId": "L00732",
        "AccountHead": "SUSPENSE ACCOUNT",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "LOANS & LIABILITIES",
        "AccountGroupId": "A002",
        "AccountId": "L00807",
        "AccountHead": "Loan from Nissar ",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "LOANS & LIABILITIES",
        "AccountGroupId": "A002",
        "AccountId": "L00997",
        "AccountHead": "Loan from Mr. Ali ",
        "AccountHeadArabic": "قرض من السيد علي",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00647",
        "AccountHead": "Al-Kifa Motars",
        "AccountHeadArabic": "الكيفا موتارس",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00648",
        "AccountHead": "NCB BANK",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00649",
        "AccountHead": "MOOSA CONT",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00650",
        "AccountHead": "ZAKARIA AL SHAGAG EST",
        "AccountHeadArabic": "",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00651",
        "AccountHead": "DOHA STAR CONTRACTING CO.",
        "AccountHeadArabic": "الدوحة ستار للمقاولات",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00652",
        "AccountHead": "ROOF TECH CONTRACTING EST.",
        "AccountHeadArabic": "مؤسسة روف تك للمقاولات.",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00654",
        "AccountHead": "TECHNICAL WING CONTACTING EST. (TWC)",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00655",
        "AccountHead": "AHMED ABDULLAH MASOUD - AAMCON",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": true
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00656",
        "AccountHead": "FAIZ YOUSUF ZAID GEN CONT EST",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00657",
        "AccountHead": "CRAFT OF WORK CONT. EST",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00781",
        "AccountHead": "AL AMTHAL FINANCING CO",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00783",
        "AccountHead": "AMYAL AL WATAN COMPNAY",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00785",
        "AccountHead": "MOHAMMAD FARHAN AL DOSSARY CONT AND TRAD CO",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00786",
        "AccountHead": "BEST FLOWER GEN CONT",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00787",
        "AccountHead": "JAAFAR MOH. AL SUBAITI GEN CONT EST",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00789",
        "AccountHead": "OVERSEAS DELTA CONT EST-JIZAN-C/O THOUSIF",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00827",
        "AccountHead": "testtttt",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00828",
        "AccountHead": "Inspection Test Services",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00856",
        "AccountHead": "Aysh Al Khalaf",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00864",
        "AccountHead": "G Cat",
        "AccountHeadArabic": "جي كات",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00881",
        "AccountHead": "Zahara Al Rasheed Contracting Establishment",
        "AccountHeadArabic": "مؤسسة زهرة الرشيد للمقاولات",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00906",
        "AccountHead": "Abdullah General Contracting Establishment",
        "AccountHeadArabic": "مؤسسة عبدالله للمقاولات العامة",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00930",
        "AccountHead": "Al Hana Water Plant",
        "AccountHeadArabic": "محطة مياه الهنا",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00952",
        "AccountHead": "Attiqur Rehman (Supplier Account)",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00988",
        "AccountHead": "Al Hamdad Contracting Company",
        "AccountHeadArabic": "شركة الحمداد للمقاولات",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L00996",
        "AccountHead": "Al Dhara Trading Company",
        "AccountHeadArabic": "شركة الدهرة التجارية",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L01002",
        "AccountHead": "Tanweer United Company Limited",
        "AccountHeadArabic": "شركة تنوير المتحدة المحدودة",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L01014",
        "AccountHead": "Maha Olayan Company Limited",
        "AccountHeadArabic": "شركة مها العليان المحدودة",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L01021",
        "AccountHead": "Herez General Contracting Establishment",
        "AccountHeadArabic": "مؤسسة هرز للمقاولات العامة",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L01030",
        "AccountHead": "Cafe Time Company",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L01045",
        "AccountHead": "Hayat Water Services",
        "AccountHeadArabic": "حياة لخدمات المياه",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L01065",
        "AccountHead": "Abhiyar Al Gassim Company",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L01070",
        "AccountHead": "Khaled Al Fadhil Company",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L01076",
        "AccountHead": "Iqbal Steel Company",
        "AccountHeadArabic": "",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L01081",
        "AccountHead": "Ashtra Food Company",
        "AccountHeadArabic": "شركة عشترا للأغذية",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L01087",
        "AccountHead": "Mansoora General Contracting Company",
        "AccountHeadArabic": "شركة المنصورة للمقاولات العامة",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L01090",
        "AccountHead": "Transworld Saudi Arabia",
        "AccountHeadArabic": "عبر العالم المملكة العربية السعودية",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L01099",
        "AccountHead": "Al Bab Trading Company",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L01100",
        "AccountHead": "Al Ababa Contracting",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L01104",
        "AccountHead": "TRADING SUPPLIER",
        "AccountHeadArabic": "المورد التجاري",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L01105",
        "AccountHead": "MATERIAL FROM CRUSHER",
        "AccountHeadArabic": "المواد من الكسارة",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L01106",
        "AccountHead": "ABDULLAH NAIM TRANSPORTATION SUPPLIER",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L01109",
        "AccountHead": "Tillal Spare Parts Company",
        "AccountHeadArabic": "شركة تلال لقطع الغيار",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L01112",
        "AccountHead": "China Chemical Company",
        "AccountHeadArabic": "",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L01121",
        "AccountHead": "Bandar Nashi Company",
        "AccountHeadArabic": "شركة بندر ناشي",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L01149",
        "AccountHead": "Fast Charge Company ",
        "AccountHeadArabic": "شركة الشحن السريع",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L01165",
        "AccountHead": "Tawarish General Contracting Company",
        "AccountHeadArabic": "شركة طوارش للمقاولات العامة",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "SUNDRY CREDITORS",
        "AccountGroupId": "A003",
        "AccountId": "L01216",
        "AccountHead": "Freelancers",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Accruals",
        "AccountGroupId": "A027",
        "AccountId": "L01154",
        "AccountHead": "Audit Fees Payable ",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00658",
        "AccountHead": "Payable - Projects Bonus-Jubail",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00659",
        "AccountHead": "Payable - Accommodation Expenses",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00660",
        "AccountHead": "Payable - Transportation Payable-jizan",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00661",
        "AccountHead": "Payable - Office Expenses",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00662",
        "AccountHead": "Payable - Salary NGC Staff 02",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00663",
        "AccountHead": "Payable - ID EXPENSES",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00664",
        "AccountHead": "Payable - Projects Bonus-Jizan",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00665",
        "AccountHead": "Payable - Allowances",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00666",
        "AccountHead": "Payable - Transportation Payable-Jubail",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00667",
        "AccountHead": "Payable - Car Petrol",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00668",
        "AccountHead": "Payable - Salary NGC Staff 01",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00669",
        "AccountHead": "Payable - Vehicles Maintenance",
        "AccountHeadArabic": "الدفع - صيانة المركبات",
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00670",
        "AccountHead": "Payable - Mobile Bill 01",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00671",
        "AccountHead": "Payable - Vehicles Rent",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00672",
        "AccountHead": "Payable - Food Expenses",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00673",
        "AccountHead": "Payable - Projects Bonus-Yanbu",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00674",
        "AccountHead": "Payable - Transportation Payable-Yanbu",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00675",
        "AccountHead": "Payable - Salary ngc 01",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00676",
        "AccountHead": "Payable - Mobile Bill 02",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00677",
        "AccountHead": "Payable - Salary ngc 02",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00678",
        "AccountHead": "Payable - Project Salary 01",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00679",
        "AccountHead": "Payable - Project Salary 02",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00680",
        "AccountHead": "Payable - Project Salary 03",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00681",
        "AccountHead": "Payable - Project Salary 04",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Other Payables & Accruals",
        "AccountGroupId": "A028",
        "AccountId": "L00682",
        "AccountHead": "Payable - Accomodation Advance",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Salary Payable",
        "AccountGroupId": "A038",
        "AccountId": "L00819",
        "AccountHead": "Salary Payable - Office Employees",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Salary Payable",
        "AccountGroupId": "A038",
        "AccountId": "L00820",
        "AccountHead": "Salary Payable - Project Employees",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Salary Payable",
        "AccountGroupId": "A038",
        "AccountId": "L00896",
        "AccountHead": "Salary Payable for KC Employees",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "VAT Input",
        "AccountGroupId": "A090",
        "AccountId": "S00100",
        "AccountHead": "VAT Input Account (VAT on Purchases)",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "VAT Input",
        "AccountGroupId": "A090",
        "AccountId": "S00300",
        "AccountHead": "VAT PAYABLE ACCOUNT",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M2",
        "MasterGroup": "Liabilities",
        "AccountGroup": "Wages Payable",
        "AccountGroupId": "A091",
        "AccountId": "L00897",
        "AccountHead": "Wages Payable Account for Project Workers",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "ACCUMULATED DEPRECIATION",
        "AccountGroupId": "A004",
        "AccountId": "L00021",
        "AccountHead": "Accumulated Depreciation",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "ACCUMULATED DEPRECIATION",
        "AccountGroupId": "A004",
        "AccountId": "L00814",
        "AccountHead": "Accumulated Depreciation - Vehicles",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "ACCUMULATED DEPRECIATION",
        "AccountGroupId": "A004",
        "AccountId": "L00815",
        "AccountHead": "Accumulated Depreciation - Equipments",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "ACCUMULATED DEPRECIATION",
        "AccountGroupId": "A004",
        "AccountId": "L00928",
        "AccountHead": "Accumulated Depreciation - Office Equipments",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "Assets - OFFICE EQUIPMENTS",
        "AccountGroupId": "A006",
        "AccountId": "L00610",
        "AccountHead": "Assets - Computers",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "Assets - OFFICE EQUIPMENTS",
        "AccountGroupId": "A006",
        "AccountId": "L00611",
        "AccountHead": "Assets - Furnitures",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "Assets - OFFICE EQUIPMENTS",
        "AccountGroupId": "A006",
        "AccountId": "L00612",
        "AccountHead": "Assets - Printers & Copy Machine",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "Assets - OFFICE EQUIPMENTS",
        "AccountGroupId": "A006",
        "AccountId": "L00926",
        "AccountHead": "Assets - Cutting Machine",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "Assets - OFFICE EQUIPMENTS",
        "AccountGroupId": "A006",
        "AccountId": "L00927",
        "AccountHead": "Asset - Laserjet Printer 1150",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "Assets - OFFICE EQUIPMENTS",
        "AccountGroupId": "A006",
        "AccountId": "L01182",
        "AccountHead": "Asset - Laserjet Printer 1500 - Color Printer",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00613",
        "AccountHead": "Vehicles - LAND CRUISER-9778",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00614",
        "AccountHead": "Vehicles - FORD EXPLORER-4037",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00615",
        "AccountHead": "Vehicles - KIA SORANTO-3283",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00616",
        "AccountHead": "Vehicles - BLAZER-313",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00617",
        "AccountHead": "Vehicles - HICE MINI BUS-4892",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00618",
        "AccountHead": "Vehicles - HICE MINI BUS-5874",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00619",
        "AccountHead": "Vehicles - KIA CIRATO - 3973",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00620",
        "AccountHead": "Vehicles - OPTIMA-7859",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00621",
        "AccountHead": "Vehicles - FORD EXPLORER-9219",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00622",
        "AccountHead": "Vehicles - TOYOTA PICK UP-6230",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00623",
        "AccountHead": "Vehicles - TOYOTA MINI BUS 7987",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00624",
        "AccountHead": "Vehicles - KIA MOHAVE - 1968",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00625",
        "AccountHead": "Vehicles - CHEVROLET TAHOE-5635",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00626",
        "AccountHead": "Vehicles - FORTUNER-6851",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00627",
        "AccountHead": "Vehicles - CAMRY-4704",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00628",
        "AccountHead": "Vehicles - FORTUNER-4705",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00629",
        "AccountHead": "Vehicles - TOYOTA HAICE-3406",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00630",
        "AccountHead": "Vehicles - TOYOTA PRADO-4766",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00631",
        "AccountHead": "Vehicles - TOYOTA HILUX-1825",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00632",
        "AccountHead": "Vehicles - TOYOTA HIACE-4122",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00633",
        "AccountHead": "Vehicles - INNOVA-7378",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00634",
        "AccountHead": "Vehicles - RAV4-1042",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00635",
        "AccountHead": "Vehicles - RAV4-1043",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00636",
        "AccountHead": "Vehicles - HIACE-7187",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00637",
        "AccountHead": "Vehicles - TOYOTA HAICE - 7188",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00638",
        "AccountHead": "Vehicles - HIACE-4403",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00639",
        "AccountHead": "Vehicles - HIACE-4401",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00640",
        "AccountHead": "Vehicles - RAV 4-8756",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00641",
        "AccountHead": "Vehicles - RAV 4 1062",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00642",
        "AccountHead": "Vehicles - RAV 5-  P N 3787",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00643",
        "AccountHead": "Vehicles - HIACE -  PLATE NO. 7990",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00644",
        "AccountHead": "Vehicles - HIACE - PLATE NO. 7991",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00645",
        "AccountHead": "Vehicles - NISSAN PATROL 6549",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00782",
        "AccountHead": "VEHICLES - LINCOLN",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
    {
        "MasterGroupId": "M3",
        "MasterGroup": "Fixed Assets",
        "AccountGroup": "VEHICLES",
        "AccountGroupId": "A008",
        "AccountId": "L00826",
        "AccountHead": "test",
        "AccountHeadArabic": null,
        "ReferenceNo": null,
        "IsLedgerObselete": false
    },
]
export const VoucherData = [
    {
        "VoucherNo": ".Opening Balance",
        "VoucherDate": "2020-01-01T00:00:00",
        "VoucherRefNo": "",
        "VoucherNarration": "Opening Balance",
        "VoucherEnteredBy": "",
        "VoucherEnteredOn": "1900-01-01T00:00:00",
        "VoucherVerifiedBy": "",
        "VoucherVerifiedOn": "1900-01-01T00:00:00",
        "VoucherApprovedBy": "",
        "VoucherApprovedOn": "1900-01-01T00:00:00",
        "VoucherEntryNo": 0,
        "AccountHead": "L00567",
        "AccountHeadName": "AXIS Inspection Services",
        "DrCr": "",
        "DrAmount": 0,
        "CrAmount": 0,
        "VoucherAmountFormatted": 1195210,
        "EntryNarration": "Opening Balance",
        "AccountGroup": "SUNDRY DEBTORS",
        "MasterGroup": "Current Assets",
        "VoucherType": "Opening Balance",
        "SysRemarks": "Opening Balance",
        "VoucherModifiedBy": "",
        "VoucherModifiedOn": "1900-01-01T00:00:00",
        "BillNo": "",
        "BillDate": "1900-01-01T00:00:00",
        "BillPaidTo": "",
        "BillRemarks": "",
        "VoucherEffectiveDate": "2020-01-01T00:00:00",
        "AccountHeadArabic": "اكسيس انسبكشن سيرفسس",
        "ReferenceNote": ""
    },
    {
        "VoucherNo": "20-00012",
        "VoucherDate": "2020-01-13T00:00:00",
        "VoucherRefNo": null,
        "VoucherNarration": "Invoiced to AXIS Inspection Services on account of Income - Trading. ()",
        "VoucherEnteredBy": "Administrator",
        "VoucherEnteredOn": "2020-01-13T17:09:35.453",
        "VoucherVerifiedBy": null,
        "VoucherVerifiedOn": null,
        "VoucherApprovedBy": null,
        "VoucherApprovedOn": null,
        "VoucherEntryNo": 50364,
        "AccountHead": "L00567",
        "AccountHeadName": "AXIS Inspection Services",
        "DrCr": "Dr",
        "DrAmount": 12202.05,
        "CrAmount": 0,
        "VoucherAmountFormatted": 12202.05,
        "EntryNarration": "Invoiced to AXIS Inspection Services on account of Income - Trading. ()",
        "AccountGroup": "SUNDRY DEBTORS",
        "MasterGroup": "Current Assets",
        "VoucherType": "Sales",
        "SysRemarks": "Income - Trading",
        "VoucherModifiedBy": null,
        "VoucherModifiedOn": null,
        "BillNo": null,
        "BillDate": null,
        "BillPaidTo": null,
        "BillRemarks": null,
        "VoucherEffectiveDate": "2019-11-01T00:00:00",
        "AccountHeadArabic": "اكسيس انسبكشن سيرفسس",
        "ReferenceNote": null
    },
    {
        "VoucherNo": "20-00163",
        "VoucherDate": "2020-09-17T00:00:00",
        "VoucherRefNo": null,
        "VoucherNarration": "Invoiced to AXIS Inspection Services on account of Income - Manpower. ()",
        "VoucherEnteredBy": "Administrator",
        "VoucherEnteredOn": "2020-09-17T17:59:34.7",
        "VoucherVerifiedBy": null,
        "VoucherVerifiedOn": null,
        "VoucherApprovedBy": null,
        "VoucherApprovedOn": null,
        "VoucherEntryNo": 52092,
        "AccountHead": "L00567",
        "AccountHeadName": "AXIS Inspection Services",
        "DrCr": "Dr",
        "DrAmount": 30900.5,
        "CrAmount": 0,
        "VoucherAmountFormatted": 30900.5,
        "EntryNarration": "Invoiced to AXIS Inspection Services on account of Income - Manpower. ()",
        "AccountGroup": "SUNDRY DEBTORS",
        "MasterGroup": "Current Assets",
        "VoucherType": "Sales",
        "SysRemarks": "Income - Manpower",
        "VoucherModifiedBy": null,
        "VoucherModifiedOn": null,
        "BillNo": null,
        "BillDate": null,
        "BillPaidTo": null,
        "BillRemarks": null,
        "VoucherEffectiveDate": "2020-09-01T00:00:00",
        "AccountHeadArabic": "اكسيس انسبكشن سيرفسس",
        "ReferenceNote": null
    },
    {
        "VoucherNo": "CRN-20-000018",
        "VoucherDate": "2020-11-15T00:00:00",
        "VoucherRefNo": "09-3972",
        "VoucherNarration": "Credit Note Issued to AXIS Inspection Services on account of Income - Trading. ()",
        "VoucherEnteredBy": "Administrator",
        "VoucherEnteredOn": "2020-11-15T09:20:40.647",
        "VoucherVerifiedBy": null,
        "VoucherVerifiedOn": null,
        "VoucherApprovedBy": null,
        "VoucherApprovedOn": null,
        "VoucherEntryNo": 52304,
        "AccountHead": "L00567",
        "AccountHeadName": "AXIS Inspection Services",
        "DrCr": "Cr",
        "DrAmount": 0,
        "CrAmount": 52500,
        "VoucherAmountFormatted": -52500,
        "EntryNarration": "Credit Note Issued to AXIS Inspection Services on account of Income - Trading. ()",
        "AccountGroup": "SUNDRY DEBTORS",
        "MasterGroup": "Current Assets",
        "VoucherType": "Journal",
        "SysRemarks": "Income - Trading",
        "VoucherModifiedBy": null,
        "VoucherModifiedOn": null,
        "BillNo": null,
        "BillDate": null,
        "BillPaidTo": null,
        "BillRemarks": null,
        "VoucherEffectiveDate": "2020-11-15T00:00:00",
        "AccountHeadArabic": "اكسيس انسبكشن سيرفسس",
        "ReferenceNote": null
    },
    {
        "VoucherNo": "321",
        "VoucherDate": "2021-02-26T00:00:00",
        "VoucherRefNo": null,
        "VoucherNarration": "",
        "VoucherEnteredBy": "Administrator",
        "VoucherEnteredOn": "2021-02-26T07:37:57.377",
        "VoucherVerifiedBy": null,
        "VoucherVerifiedOn": null,
        "VoucherApprovedBy": null,
        "VoucherApprovedOn": null,
        "VoucherEntryNo": 52961,
        "AccountHead": "L00567",
        "AccountHeadName": "AXIS Inspection Services",
        "DrCr": "Dr",
        "DrAmount": 10,
        "CrAmount": 0,
        "VoucherAmountFormatted": 10,
        "EntryNarration": "",
        "AccountGroup": "SUNDRY DEBTORS",
        "MasterGroup": "Current Assets",
        "VoucherType": "Sales",
        "SysRemarks": " Income - Equipment Rental",
        "VoucherModifiedBy": "Administrator",
        "VoucherModifiedOn": "2021-02-26T07:38:16.207",
        "BillNo": null,
        "BillDate": null,
        "BillPaidTo": null,
        "BillRemarks": null,
        "VoucherEffectiveDate": "2021-02-26T00:00:00",
        "AccountHeadArabic": "اكسيس انسبكشن سيرفسس",
        "ReferenceNote": null
    },
    {
        "VoucherNo": "CRN-23-000003",
        "VoucherDate": "2023-05-06T00:00:00",
        "VoucherRefNo": "098",
        "VoucherNarration": "",
        "VoucherEnteredBy": "Saju Joy",
        "VoucherEnteredOn": "2023-05-06T09:28:40.24",
        "VoucherVerifiedBy": null,
        "VoucherVerifiedOn": null,
        "VoucherApprovedBy": null,
        "VoucherApprovedOn": null,
        "VoucherEntryNo": 55109,
        "AccountHead": "L00567",
        "AccountHeadName": "AXIS Inspection Services",
        "DrCr": "Cr",
        "DrAmount": 0,
        "CrAmount": 1725,
        "VoucherAmountFormatted": -1725,
        "EntryNarration": "",
        "AccountGroup": "SUNDRY DEBTORS",
        "MasterGroup": "Current Assets",
        "VoucherType": "Journal",
        "SysRemarks": "Income - Equipment Rental",
        "VoucherModifiedBy": null,
        "VoucherModifiedOn": null,
        "BillNo": null,
        "BillDate": null,
        "BillPaidTo": null,
        "BillRemarks": null,
        "VoucherEffectiveDate": "2023-05-06T00:00:00",
        "AccountHeadArabic": "اكسيس انسبكشن سيرفسس",
        "ReferenceNote": null
    }
] 